var config = {
    version: 'BuildConference/1.0.0', // this helps to identify telemetry generated by the samples
    apiKey: 'a42fcebd-5b43-4b89-a065-74450fb91255', // SDK DF
    apiKeyCC: '9c967f6b-a846-4df2-b43d-5167e47d81e1' // SDK+CC DF
};
