/// <reference path="Person.d.ts" />
/// <reference path="Reason.d.ts" />

declare module jCafe {

    // Note: tsc doesn't support string enums; see /TypeScript/issues/1003

    /** These are the various types of activities that are generated by Conversation.
     *
     *       "TextMessage"
     */
    export type ActivityType = string;

    /** Status of a activity item
     *
     *       "Pending"
     *       "Succeeded"
     *       "Failed" 
     */
    export type ActivityStatus = string;

    /** Direction of an activity item
     *
     *       "Incoming"
     *       "Outgoing"
     */
    export type Direction = string;

    /**
     * A general purpose conversation activity item like a text message, a video call, etc.
     */
    export interface ConversationActivityItem {
        
        type: Property<ActivityType>;
        timestamp: Property<Date>;
        status: Property<ActivityStatus>;
    }

    export interface TextMessageActivityItem extends ConversationActivityItem {
        direction: Property<Direction>;
        sender: Person;
        /** the text/plain representation of the message 
            If the message is html only the sdk creates a text version of the message as well */
        text: Property<string>;
        /** the text/html representation of the message 
            If the message is text only the sdk creates a html version of the message as well */
        html: Property<string>;
    }
}